name: build

on:
  push:
    branches: main

env:
  release_version: "0.1a"

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ghcr.io/exnihlio/helloworld:${{ release_version }} ghcr.io/exnihlio/helloworld:latest

      - name: Push
        run: docker push

      